### ISSUE TITLE
Is there a benchmark or something like that?

### ISSUE THREAD

**Issue by nanmu42** [ColinEberhardt/d3-wasm-force#1]
Hi,

Good job and I am really impressed!

Just wondering, is this wasm version faster enough than the JavaScript version?

regards

**Comment by yGuy** [comment]
I, too, would be interested in seeing some performance comparisons, after all, if the performance boost is negligible (and the fact that you don't make any statement, anywhere, indicates that there is not that much of a performance improvement) compared to the JavaScript version, there is hardly anything left that would make me write code in that severely limited JS/TS variant.

**Comment by ColinEberhardt** [comment]
I haven't performance benchmarked this code specifically, because it would not be a like-for-like comparison with the d3-force code. I skipped a few checks and edge cases for the sake of brevity.

I have however made same performance measurements for a simple mandelbrot algorithm:

![image](https://user-images.githubusercontent.com/1098110/34044774-45cad5b0-e19e-11e7-9e29-8536b63f2947.png)

See the related blog post here:

http://blog.scottlogic.com/2017/10/17/wasm-mandelbrot.html

I was unable to make any significant performance improvement over JavaScript. Although this is likely due to the immature nature of the WebAssembly runtime, and the algorithm I was benchmarking being quite easy to optimise by the JS compilers.

I've seen others claim x10 - x100 speed increase with WebAssembly. I am confident that they are all wrong!

For a more accurate indication of the speed of WebAssembly I'd recommend this publication:

https://blog.acolyer.org/2017/09/18/bringing-the-web-up-to-speed-with-webassembly/

> WebAssembly is on average 33.7% faster than asm.js, with validation taking only 3% of the time it does for asm.js

> WebAssembly binaries are also compact, being on average 62.5% the size of asm.js, and 85.3% of native x86-64 code.

As you can see, runtime gains are marginal, whereas compact binary size, rapid validation and predictable runtime performance are the bigger gains/

**Comment by yGuy** [comment]
Thanks for the info - I had the same feeling about this (unless your code *only* does number crunching, it will not benefit from anything like that much). In fact your very own demo at least in Chrome the webassembly version seems to run slower than the JavaScript variant. At least that what the Chrome performance profiler tells me - and it feels like that, too, actually.

Right now, I don't think this (webassembly) is something one should be considering except for really rare edge cases. JavaScript size may be one thing edge case, but when do you really have a web application that only does number crunching and needs to load fast at the same time? Bitcoin mining ads, maybe?.... Looks like yet another toy for the UA devs that don't care about the _real_ problems in the web platform. JavaScript number crunching speed is not part of these problems.

**Comment by nanmu42** [comment]
Thanks for the finely detailed explanation.
Maybe this is the future of JavaScript. :)
